### ISSUE TITLE
"(0 , stats_base_dists_beta_cdf_1.default) is not a function" in ts-jest

### ISSUE THREAD

**Issue by Quanyails** [stdlib-js/stdlib#1038]
### Description

Cannot import and call Beta Distribution CDF function from ts-jest.

### Related Issues

Might be related to #508?

### Questions

No.

### Reproduction

1. Set up a ts-jest project ([docs](https://jestjs.io/docs/getting-started#via-ts-jest)).
2. Create the following test.
3. Run the test in Jest.

```shell
// confidence.test.ts
import cdf from "@stdlib/stats-base-dists-beta-cdf";

test("confidence", () => {
    cdf(0.5, 1, 2);
});
```

### Expected Results

```shell
Passing test + no error.
```

### Actual Results

```shell
When running the test, I encounter the following error message:


(0 , stats_base_dists_beta_cdf_1.default) is not a function
TypeError: (0 , stats_base_dists_beta_cdf_1.default) is not a function
```

### Version

0.0.7

### Environments

Node.js

### Node.js / npm Version

20.0.0

### Platform

Windows 11 build 22621.1848

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by Planeshifter** [comment]
This is likely due to how your `tsconfig.json` is configured and how TypeScript resolves CommonJS modules. It looks as if the CDF function is made available under the `default` property such that the below likely works for you as-is:

```ts
import cdf from "@stdlib/stats-base-dists-beta-cdf";

test("confidence", () => {
    cdf.default(0.5, 1, 2);
});
```

You should be able to change the `esModuleInterop` setting to get around this. Please have a look at the documentation for more information about why this happens:

https://www.typescriptlang.org/tsconfig#esModuleInterop

Please let us know if that doesn't resolve the issue.

**Comment by Quanyails** [comment]
Thanks for the quick response! Yep, including `esModuleInterop` in my tsconfig resolves the issue. Good to know this is the recommended solution for this environment.
