### ISSUE TITLE
Macro not working for rendering equations in readmes

### ISSUE THREAD

**Issue by steff456** [stdlib-js/stdlib#1043]
### Description

Encountered an error in readmes that are using `\operatorname` macro.

For example, https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/erfc

### Related Issues

No

### Questions

No.

### Reproduction

```shell
- Open a readme of any package that is using `\operatorname`
```

### Expected Results

```shell
- The equation should be rendered correctly without any error
```

### Actual Results

```shell
The current readme in develop is rendering as,

<img width="1283" alt="image" src="https://github.com/stdlib-js/stdlib/assets/20992645/61346d1b-481f-4bae-a766-f3d8a3050329">
```

### Version

develop branch

### Environments

Chrome

### Browser Version

113.0.5672.126

### Platform

macOS

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
@Planeshifter It looks like whatever GitHub uses to render math equations does not support `\operatorname`. Can you investigate? If so, we will need to find a workaround (e.g., using `mathrm`, etc) to achieve the equivalent of `operatorname`.

**Comment by Planeshifter** [comment]
GitHub uses MathJax for rendering LaTeX equations; MathJax requires the [ams](https://docs.mathjax.org/en/latest/input/tex/extensions/ams.html) extension to be loaded in order to render `\operatorname`. It looks like GitHub doesn't load this extension, so we will need to find a workaround. Using `mathrm` seems like the obvious candidate. As I see it, we have two options: Replace usage of `\operatorname` in the source equations, or update the [remark plugin](https://github.com/stdlib-js/stdlib/blob/ab8801abb8c86b3ef07a242382db9ef1d8b76cbc/lib/node_modules/%40stdlib/_tools/remark/plugins/remark-img-equations/lib/insert_equations.js#L98) to swap out occurrences of `\operatorname` in the code. Since these two behave slightly different with respect to spacing etc., I am leaning towards updating the equations, while making sure they are looking properly.

**Comment by kgryte** [comment]
@Planeshifter I wonder if there is a public issue tracker where we can report this and request that the `ams` extension be loaded.

**Comment by kgryte** [comment]
@Planeshifter Maybe we can use `\mathop{\mathrm{...}}` as a [workaround](https://tex.stackexchange.com/questions/84302/what-is-the-difference-of-mathop-operatorname-and-declaremathoperator)?

**Comment by kgryte** [comment]
@Planeshifter I'd lean toward updating the remark plugin, rather than updating the equations. `\operatorname` is the right choice and is still used by the HTML docs, as we load the ams extension there. I'd rather not do the workaround just to placate GitHub's quirks.

**Comment by kgryte** [comment]
@Planeshifter Has this now been addressed? Or is there still work to be done?

**Comment by Planeshifter** [comment]
@kgryte No, it's taken care of. Closing...
