### ISSUE TITLE
Coverage report link is broken

### ISSUE THREAD

**Issue by rotu** [stdlib-js/stdlib#1055]
### Description

In [README.md](https://github.com/stdlib-js/stdlib/blob/develop/README.md#resources) and [CONTRIBUTING.md](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md#writing-tests), the Code coverage link brings you to [a codecov page](https://app.codecov.io/github/stdlib-js/stdlib/branch/develop) that does not provide the expected coverage info. It says:

> This repo has been deactivated
> Contact an administrator of your git organization to grant write-permissions in your git-provider for this repository.

### Questions

No.

### Demo

https://app.codecov.io/github/stdlib-js/stdlib/branch/develop

### Actual Results

```shell
![image](https://github.com/stdlib-js/stdlib/assets/119948/0a882d33-3251-48e3-bfcd-78b7e49012fe)
```

### Environments

N/A

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
@rotu Thanks for flagging! Looks like Codecov had changed how it worked with Git repos a while back and we had yet to migrate over. This should now be fixed. The links should work.

Actually generating and uploading the actual coverage report to Codecov is, however, not working at the moment. Namely because we don't run the full test suite across the entire project during CI due to the sheer number of tests the main repository contains.

I'll go ahead and close this as completed. Uploading accurate reports is a separate follow-on task.
