### ISSUE TITLE
Not an issue... I just wanted to reach out.

### ISSUE THREAD

**Issue by ashleydavis** [stdlib-js/stdlib#156]
Hi, I think this library looks really promising and I'm very keen to follow it!

Sorry for raising the issue, I really just wanted to reach out, tell you what I'm doing and find out more about your project.

I've built an open source JavaScript toolkit for data wrangling: http://www.data-forge-js.com/

I'm also the author of the upcoming book Data Wrangling with JavaScript: https://www.manning.com/books/data-wrangling-with-javascript

I'd love to talk to the creator of this library about how it came about, where it's going and your thoughts on the JavaScript data wrangling ecosystem. 

Please email me on ashley@codecapers.com.au if you are interested in chatting about it.

**Comment by kgryte** [comment]
@ashleydavis There is no one creator of this library. Should you want to contact contributors, their contact information can be deduced from GitHub. Otherwise, another channel is Gitter, a link to which can be found on the project README.

We certainly appreciate your interest in the project, but, as this is not an actionable issue, I'm going to close.

**Comment by ashleydavis** [comment]
@kgryte Is there anyone in particular that you could recommend I talk to about it?

**Comment by kgryte** [comment]
I can only speak for myself. Feel free to contact me via email, and I can direct you further from there.
