### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by DanielRuf** [stdlib-js/stdlib#252]
The CI is currently failing, see https://travis-ci.org/stdlib-js/stdlib/builds/483724476

**Comment by kgryte** [comment]
@DanielRuf Yes, this is a lingering issue, which requires some engineering work. Namely, we need to devise a means for reducing the test load. Currently, because the project has so many tests, builds frequently either time out or encounter memory limitations. Unfortunately, we've yet to allocate development time to addressing Travis CI builds due to limited bandwidth. :(

**Comment by DanielRuf** [comment]
The max timeout for Travis can be increased using `travis_wait` (not really increased but works as workaround).

https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

```
If you have a command that doesn’t produce output for more than 10 minutes, you can prefix it with travis_wait, a function that’s exported by our build environment. For example:

    install: travis_wait mvn install
YAML
spawns a process running mvn install. travis_wait then writes a short line to the build log every minute for 20 minutes, extending the amount of time your command has to finish.

If you expect the command to take more than 20 minutes, prefix the command with travis_wait n where n is the number of minutes extend the waiting time by.

Continuing the example above, to extend the wait time to 30 minutes:

    install: travis_wait 30 mvn install
YAML
We recommend careful use of travis_wait, as overusing it can extend your build time when there could be a deeper underlying issue. When in doubt, file a ticket or email us first to see if something could be improved about this particular command first.

Limitations of travis_wait #
travis_wait works by starting a process, sending it to the background, and watching the background process. If the command you pass to travis_wait does not persist, then travis_wait does not extend the timeout.
```

**Comment by kgryte** [comment]
This is already done (in an equivalent manner). See https://github.com/stdlib-js/stdlib/blob/1c2eb2cc4ff79cc27c88005ee1913ed44210886f/.travis.yml#L147 and https://github.com/stdlib-js/stdlib/blob/1c2eb2cc4ff79cc27c88005ee1913ed44210886f/tools/ci/travis/script#L60. By timeout, I mean the maximum allowed time for any build, even if output is being generated.

**Comment by DanielRuf** [comment]
> By timeout, I mean the maximum allowed time for any build, even if output is being generated

This is set to 50 minutes for free opensource projects.

The log still says that it hit the 10 minute output timeout.

**Comment by DanielRuf** [comment]
Why creating a heartbeat function? `travis_wait` should be sufficient and work. Because I think this is how it should work.

**Comment by kgryte** [comment]
As mentioned in my original response, there are multiple reasons the builds fail: one of them is hitting the 50 minute limit. The other is that jobs randomly fail arbitrarily due to (as has been deduced) hitting implicit memory limits (shared hosts). A third reason, which was not stated in the original response, is due to "flaky" tests due to precision comparisons.

We have a heartbeat function because (a) we wrote it before `travis_wait` was a thing, (b) it allows us to control logging, and (c) makes for more consistent behavior across the various CI services we use.

**Comment by DanielRuf** [comment]
Hm, so either we move to an alternative like Circle CI or we need a paid Travis CI instance.

**Comment by kgryte** [comment]
No, not necessarily. In short, a "smarter" strategy needs to be developed. For example, selective test running and/or random sampling, which would reduce overall test load.
