### ISSUE TITLE
Sponsor button is broken

### ISSUE THREAD

**Issue by nhnicwaller** [stdlib-js/stdlib#259]
## Description

The **❤️Sponsor** button (shown at the top of every page on [this GitHub repo](https://github.com/stdlib-js/stdlib)) is broken.

## Expected Result

The Sponsor button doesn't present an error message.

## Actual Result

The Sponsor button presents an error message.

> Some errors were encountered when parsing the FUNDING.yml file:
> Some users provided are not enrolled in GitHub Sponsors. Apply to the beta.
> Learn more about formatting FUNDING.yml.

<img width="433" alt="Screen Shot 2019-07-31 at 4 50 48 PM" src="https://user-images.githubusercontent.com/42976427/62255815-ba710e00-b3b3-11e9-896d-ef073dd74bb3.png">

## Steps to Reproduce

Navigate to [stdlib-js/stdlib on GitHub](https://github.com/stdlib-js/stdlib/) and click the **Sponsor** button.

**Comment by kgryte** [comment]
@nhnicwaller Thanks for reporting this issue. This is because the GitHub funding program is still in beta, and, unfortunately, project maintainers have yet to be accepted into the program. 😢

We went ahead and added the funding file in anticipation of acceptance, but are still waiting to hear back. 🤷‍♂️

**Comment by kgryte** [comment]
Closing this out, as we've been accepted! Can now sponsor project maintainers via GitHub's funding program. :)
