### ISSUE TITLE
`@stdlib/string`: `startcase` function does not work when the input string is fully uppercase

### ISSUE THREAD

**Issue by KBeDevel** [stdlib-js/stdlib#491]
### Description

Encountered an unexpected result when trying to change the case of an enumerator key

The string is obtained using the logic: `Enumerator[Enumerator.EnumeratorKey]`

### Related Issues

No related issues found (yet)

### Questions

No.

### Demo

https://codesandbox.io/s/agitated-hill-v37msg?file=/src/App.tsx

### Reproduction

```shell
- Define/import an enumerator with uppercase string keys
- Use the enumerator value to get the enumerator key (`startcase(Enumerator[Enumerator.ENUMERATOR_KEY])`)
```

### Expected Results

```shell
Execute `startcase(StatusCodes[StatusCodes.UNAUTHORIZED])` and obtain `'Unauthorized'`
```

### Actual Results

```typescript
// The enumerator is exported by the `http-status-codes` library

enum StatusCodes { // Enumerator structure for reference
  ACCEPTED = 202,
  BAD_GATEWAY = 502,
  // ...
  UNAUTHORIZED = 401,
  // ...
};

startcase(StatusCodes[StatusCodes.UNAUTHORIZED]); // -> UNAUTHORIZED

startcase(StatusCodes[StatusCodes.UNAUTHORIZED].toString()) // -> UNAUTHORIZED

startcase(`${StatusCodes[StatusCodes.UNAUTHORIZED]}`); // -> UNAUTHORIZED

startcase("UNAUTHORIZED"); // -> UNAUTHORIZED
```

The workaround is:

```typescript
startcase(StatusCodes[StatusCodes.UNAUTHORIZED].toLowerCase()); // -> Unauthorized
```

### Version

"@stdlib/string": "^0.0.13"

### Environments

Firefox, Chrome, Microsoft Edge

### Node.js / npm Version

noed@17.9.0 / yarn@3.2.0 (npm@8.5.5)

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by Planeshifter** [comment]
Thank you for filing this issue and providing a detailed description! 

The current behavior is intentional and matches our other `*case` functions such as `camelcase` and `pascalcase` in that it leaves uppercase character appearing in the middle of a word intact  
(e.g., see [[1]](https://github.com/stdlib-js/stdlib/blob/5323416e8a90b30f9d7b40d91b280fe4e2978fcf/lib/node_modules/%40stdlib/string/camelcase/test/test.js#L82), [[2]](https://github.com/stdlib-js/stdlib/blob/5323416e8a90b30f9d7b40d91b280fe4e2978fcf/lib/node_modules/%40stdlib/string/pascalcase/test/test.js#L82)).

We tried to convey this via the package description, which is:

> Capitalize the first letter of each word in a string.

and have a [unit test included to that effect](https://github.com/stdlib-js/stdlib/blob/5323416e8a90b30f9d7b40d91b280fe4e2978fcf/lib/node_modules/%40stdlib/string/startcase/test/test.js#L83).

We suggest you stick to first lowercasing the string before passing it into the `startcase` function in order to achieve the desired behavior.
