### ISSUE TITLE
Fix links in README.md and related files

### ISSUE THREAD

**Issue by labiej** [stdlib-js/stdlib#86]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

* [x] Read and understood the [Code of Conduct][code-of-conduct].
* [x] Searched for existing issues and pull requests.
* [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
* [x] If this is a feature request, the issue name begins with `RFC: `.

## Description

> Description of the issue (or feature request).

The links to e.g. the contributing guidelines in README.md are broken. They are pointing to the master branch.

## Related Issues

> Does this issue (or feature request) have any related issues?

No.

## Questions

> Any questions for reviewers?

Should this be fixed in develop or is it made this way in anticipation for a first alpha which will be living on master?

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/master/CODE_OF_CONDUCT.md
[faq]: https://github.com/stdlib-js/stdlib/blob/master/FAQ.md

**Comment by kgryte** [comment]
@labiej That the links point to `master` is intentional. And you are right, that the links do so is in anticipation of when we finally merge into `master`.

But in thinking about this, given that `develop` is and will continue to be the main branch, we should update to point to `develop` as doing so is more reflective of the current state of development practice. I will update the links accordingly.
