### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/spence`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#894]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/spence`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/spence).

```c
double stdlib_base_spence( const double x );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Jordan-Gallivan** [comment]
I'd like to take this one on as well.

**Comment by kgryte** [comment]
Thanks, @Jordan-Gallivan, that would be great!

**Comment by kgryte** [comment]
@Jordan-Gallivan This implementation will be a touch more involved than your previous contributions.

You can use [`asin`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/@stdlib/math/base/special/asin), as a reference. Namely, it will involve autogenerating some polynomial expressions, which requires a special [comment syntax](https://github.com/stdlib-js/stdlib/blob/d115362a80635761a217131b678abc7c21d32f49/lib/node_modules/%40stdlib/math/base/special/asin/src/main.c#L41) and running a [script](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/@stdlib/math/base/special/asin/scripts/evalrational.js). However, instead of `evalrational`, you'll need to update [`evalpoly`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/@stdlib/math/base/special/spence/scripts/evalpoly.js). You can consult other special math functions which have a C implementation and an evalpoly script.

Let us know if you have questions!

**Comment by kgryte** [comment]
Also, I'm happy to hop on a Google Meet to discuss further.

**Comment by Jordan-Gallivan** [comment]
@kgryte I definitely might need more coaching than the previous implementations but I think I'm up to the task. I'll comb through everything tonight and let you know if I have any questions before I jump in, in which case I'll definitely take you up on the Google Meet offer.

**Comment by kgryte** [comment]
Sounds good! Thanks for taking the initiative and working on this!

**Comment by Jordan-Gallivan** [comment]
@kgryte wanted to drop you a line and let you know that I'm still down to work this problem, I just got slammed last week with school/the internship search.

**Comment by kgryte** [comment]
@Jordan-Gallivan No worries!

**Comment by Jordan-Gallivan** [comment]
@kgryte just submitted a PR.  You weren't kidding, this was a doozie.  I added a few questions in the PR so please lemme know what I can fix.
