### ISSUE TITLE
make: *** No rule to make target on windows

### ISSUE THREAD

**Issue by parth121101** [stdlib-js/stdlib#997]
### Description

Encountered an error when trying to build stdlib-js on windows PC using git bash.
```console
Parth Mistry@LAPTOP-RJGTJ6LL MINGW64 ~/Desktop/stdlib (develop)
$ make install-node-modules
Makefile:226: Mistry/Desktop/stdlib/tools/make/Makefile: No such file or directory
make: *** No rule to make target 'Mistry/Desktop/stdlib/tools/make/Makefile'.  Stop.
```

### Questions

No.

### Version

Forked latest main

### Environments

N/A

### Node.js / npm Version

8.15.0

### Platform

WIndows

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
One thing to note is that there seems to be a path issue. Namely, your user name has a space in it, which is affecting path resolution.

**Comment by kgryte** [comment]
@Planeshifter will be following up to determine whether there is something we can do to address the space issue.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by Visbhavesh** [comment]
hello please assign it to me

**Comment by Lalith514** [comment]
he error message you encountered suggests that the Makefile is unable to locate the necessary file or directory to proceed with the build process.

once check these @parth121101 


Make sure you have cloned the stdlib repository correctly. Double-check that the repository is present in the ~/Desktop/stdlib directory.

Verify that you have the necessary dependencies and tools installed on your Windows PC. Ensure that you have Git Bash, Node.js, and Make installed and properly configured.

Open the Makefile located in the stdlib repository and look for the line that references Mistry/Desktop/stdlib/tools/make/Makefile. It seems like an incorrect or incomplete path.

Update the path in the Makefile to the correct relative path from the current directory. In your case, if the Makefile is located in the ~/Desktop/stdlib directory, the path should be tools/make/Makefile instead of Mistry/Desktop/stdlib/tools/make/Makefile.

Save the changes to the Makefile and try running the make install-node-modules command again in Git Bash.

**Comment by kgryte** [comment]
@Lalith514 Thanks for commenting; however, the guidance you have provided above is not correct and is likely to mislead. The issue is due to having a space in the path.

Question: based on your response, I am wondering if your comment has been auto-generated using, e.g., ChatGPT. Is my suspicion correct?

**Comment by Aditishukla29** [comment]
Path issues

**Comment by Aditishukla29** [comment]
Pls write right path

**Comment by gouravgodla** [comment]
> ### Description
> Encountered an error when trying to build stdlib-js on windows PC using git bash.
> 
> ```
> Parth Mistry@LAPTOP-RJGTJ6LL MINGW64 ~/Desktop/stdlib (develop)
> $ make install-node-modules
> Makefile:226: Mistry/Desktop/stdlib/tools/make/Makefile: No such file or directory
> make: *** No rule to make target 'Mistry/Desktop/stdlib/tools/make/Makefile'.  Stop.
> ```
> 
> ### Related Issues
> _No response_
> 
> ### Questions
> No.
> 
> ### Demo
> _No response_
> 
> ### Reproduction
> _No response_
> 
> ### Expected Results
> _No response_
> 
> ### Actual Results
> _No response_
> 
> ### Version
> Forked latest main
> 
> ### Environments
> N/A
> 
> ### Browser Version
> _No response_
> 
> ### Node.js / npm Version
> 8.15.0
> 
> ### Platform
> WIndows
> 
> ### Checklist
> * [x]  Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
> * [x]  Searched for existing issues and pull requests.

It seems like you are trying to build stdlib-js on Windows PC using git bash and encountered an error. The error message you provided indicates that the make command is unable to find the Makefile in the specified directory². 

One possible solution is to make sure that you are calling git bash from a regular CMD session and not from other alternative shells². Another solution is to open git bash by calling it with the path to PortableGit-2.6.1-64-bit/git-bash.exe which will set HOME properly¹.

If you are still facing issues, you can try checking if the SSL certificate of the Git server is self-signed³. 

I hope this helps!
(1) make: *** No rule to make target on windows #997 - GitHub. https://github.com/stdlib-js/stdlib/issues/997 Accessed 22/5/2023.
(2) GIT bash showing "build failed" error in windows - Stack Overflow. https://stackoverflow.com/questions/33196419/git-bash-showing-build-failed-error-in-windows Accessed 22/5/2023.
(3) SSL cerfrificaion problem: 'unable to get local issuer ... - Komodor. https://komodor.com/learn/how-to-fix-ssl-certificate-problem-unable-to-get-local-issuer-certificate-git-error/ Accessed 22/5/2023.
(4) GitHub - stdlib-js/stdlib: Standard library for JavaScript and Node.js.. https://github.com/stdlib-js/stdlib Accessed 22/5/2023.

**Comment by Planeshifter** [comment]
As the [development guide](https://github.com/stdlib-js/stdlib/blob/18482b3feda6ce8241e0b72bb4715564e7931277/docs/development.md#download) states

> To acquire the source code, first navigate to the parent directory into which you want to place the project [Git](http://git-scm.com/) repository. Because of this project's heavy reliance on [GNU make](https://www.gnu.org/software/make/), the directory path should not include spaces or any other shell meta characters such as $ or :, as these characters will cause [GNU make](https://www.gnu.org/software/make/) and the installation process to fail.

To avoid the encountered issues, please ensure to have the git repository cloned in a directory path not containing spaces. We will look into updating our documentation to make this restriction more prominent.

We looked into refactoring our `make` recipes to accommodate spaces in directory paths, but this proved to be infeasible. 

Thanks for your patience! Closing this issue.
